[package]
name = "kaloron"
version = "0.0.1"
description = "Schema-driven binary serialization framework with versioning"
license = "MIT"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
blake3 = { workspace = true }
seq-macro = { workspace = true }
kaloron-macro = { workspace = true }
